config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'contact_us/new'
  get 'messages', to: 'contat_us#index', as: :messages
  post 'messages', to: 'contact_us#create'

  # Defines the root path route ("/")
  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  after_create_commit -> { broadcast_append_to :messages, partial: 'contact_us/message', locals: { message: self } }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contact_us_controller.rb
# frozen_string_literal: true

class ContactUsController < ApplicationController
  def new
    @message = Message.new
  end

  def index; end

  # rubocop: disable Metrics/MethodLength, Rails/I18nLocaleTexts
  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:messages, partial: 'contact_us/message',
                                                              locals: { message: @message })
        end
      end
    else
      flash[:error] = 'Cannot save message'
      redirect_to welcome_path
    end
  end
  # rubocop: enable Metrics/MethodLength, Rails/I18nLocaleTexts

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @messages = Message.order(:id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contact_us/_message.html.erb
<div id="<%= dom_id(message) %>">
  <p>
    <%= message.content %>
  </p>
</div>

app/views/contact_us/new.html.erb
<turbo-frame id="contact-us-form">
  <h1>ContactUs#new</h1>
  <h2>Fill in the following details</h2>

  <%= form_for @message do |f| %>
    <%= f.text_area :content %>
    <br/>
    <%= f.submit %>
  <% end %>
</turbo-frame>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modern Rails Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div id="app" data-controller="hello">
      <strong data-hello-target="greet"></strong>
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Dropdown item</a></li>
    <li><a class="dropdown-item" href="#">Dropdown item</a></li>
    <li><a class="dropdown-item" href="#">Dropdown item</a></li>
  </ul>
</div>

<%= turbo_stream_from "messages" %>

<%= turbo_frame_tag "contact-us-form" do %>
  <%= link_to 'Contact Us', contact_us_new_path %>
<% end %>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render partial: 'contact_us/message', locals: { message: message } %>
  <% end %>
</div>